### ISSUE TITLE
Vue Scaffolding templates?

### ISSUE THREAD

**Issue by aadrian** [matrei/pingcrm-grails#1]
Hi,

Any chance having some (Vue) Scaffolding templates (to be used for dynamic and/or static scaffolding) ?

Manually writing so much VueJS code for the CRUD (index/view/create/edit views) seems kind of daunting considering that in the classical (monolith) Webapp this can be taken care of by the scaffolding and one needs only to install and update the templates a little. 

Thank you.

**Comment by matrei** [comment]
Hi Adrian!
That would certainly be possible, but perhaps better suited in a Grails Plugin or Profile.
This application (Ping CRM) only serves as a demonstration of using the Grails Inertia Plugin.

**Comment by aadrian** [comment]
> ...but perhaps better suited in a Grails Plugin or Profile.

For sure that would be the luxury version :) .


A simple and typical approach with all Grails apps however, is to just install and commit the default templates with:
```bash
grails> install-templates
```
and than modify them to be usable by the scaffolding according the project's requirements (e.g. extra links and buttons, different form layouts, roles checking, etc). 

If the amount of "application users" is small, than **Dynamic Scaffolding** is even better for code maintenance - since there's only the "override code" in GIT. 
Also, static scaffolding is more work since it can't be easily be separated on the file level (e.g. to another source base like `/src-gen/*` for easy maintenance) .


> This application (Ping CRM) only serves as a demonstration of using the Grails Inertia Plugin.

Of course. 
Having the templates here (too), would also demonstrate the advantage of using Grails and **this** Adapter compared to the other Inertia Adapters :) . 



Thank you.

**Comment by matrei** [comment]
I'll think about adding template scaffolding to the inertia plugin or a new profile. But this repo is just an example application using the inertia plugin so I'm not going to add it here. Thanks you for reaching out!
